sudo: false

language: cpp

compiler:
    - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - doxygen
      - g++-5
      - libgtest-dev
      - valgrind

before_install:
    - cat .travis.yml

install:
    - pwd
    - ls -al
    - mkdir gtest
    - cd gtest
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - pwd
    - ls -al
    - cd -

before_script:
    - date
    - uname -a
    - printenv | sort
    - cat makefile

script:
    - make travis
